apiVersion: batch/v1
kind: Job
metadata:
  name: perl
spec:
  ttlSecondsAfterFinished: 30
  template:
    spec:
      containers:
      - name: pl
        image: perl
        command: ["perl", "-Mbignum=bpi", "-wle","print bpi(2000)"]
      restartPolicy: Never